name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - system: x86_64-linux
            runner: [linux, X64, drakon64/github-actions-runner-aws, EC2-r7a.large, EBS-30GB]
          - system: aarch64-linux
            runner: [linux, ARM64, drakon64/github-actions-runner-aws, EC2-r8g.large, EBS-30GB]

    name: Build - ${{ matrix.architecture.system }}
    runs-on: ${{ matrix.architecture.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v13

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-cosmic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cosmic

      - env:
          SYSTEM: ${{ matrix.architecture.system }}
          ATTRIBUTE: ${{ matrix.attribute }}
        run: |
          nix -vL build --show-trace --cores 2 --max-jobs 1 --system "$SYSTEM" .#vm.closure
