name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_aarch64_linux:
    name: Build - aarch64-linux
    runs-on: [linux, ARM64, drakon64/github-actions-runner-aws, EC2-r7g.large, EBS-30GB]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v11

      - run: nix -vL build --show-trace --cores 1 --max-jobs 1 .#vm.closure
