name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build - x86_64-linux - vm-stable.closure
    runs-on: [linux, x64, ktisis, ktisis-n4-highmem-8, ktisis-30GB]

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-cosmic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cosmic

      - run: nix build --cores 8 --max-jobs 1 --system x86_64-linux .#vm-stable.closure
