name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        architecture:
          - system: x86_64-linux
            runner: [linux, X64, drakon64/github-actions-runner-aws, EC2-m7a.2xlarge, EC2-Spot, EBS-30GB, EBS-32GB-Swap]
          - system: aarch64-linux
            runner: [linux, ARM64, drakon64/github-actions-runner-aws, EC2-m8g.2xlarge, EC2-Spot, EBS-30GB, EBS-32GB-Swap]
        attribute:
          - vm.closure
          - vm-stable.closure

    name: Build - ${{ matrix.architecture.system }} - ${{ matrix.attribute }}
    runs-on: ${{ matrix.architecture.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-cosmic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cosmic

      - env:
          SYSTEM: ${{ matrix.architecture.system }}
          ATTRIBUTE: ${{ matrix.attribute }}
        run: |
          nix build --cores 8 --max-jobs 1 --system "$SYSTEM" ".#$ATTRIBUTE"
